### PR TITLE
Refactor code quality issues

### PR DESCRIPTION
**Pull request by akshgpt7**
## Description

Hi, I ran [DeepSource](https://deepsource.io/) analysis on my fork of the repo, and found some interesting [code quality issues](https://deepsource.io/gh/akshgpt7/bayes-skopt/) that can improve the general code quality here. This PR fixes a few of the issues detected.

#### Summary of changes:
- Replace unnecessary `dict()` calls with literals.
- Refactor unnecessary `else/elif` after `return` statement inside `if`.
- Remove unnecessary `return` statements.
- Remove inheritance of `object` from base class.

## Motivation and Context

There were quite a few anti-patterns and a few performance issues that can be easily dealt with.

## Does this close/impact existing issues?

No

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.

### CODE REVIEW

**Comment by kiudee** [comment]
Thank you for the pull request and the outreach. In general I try to keep projects as slim as possible with respect to external source code analysis. I went over all of the code quality issues DeepSource reported for the project and most of them are very minor. Do you have some examples where DeepSource finds an interesting code quality issue (maybe from some other repository) which other tools like flake8 + extensions do not find?

**Comment by akshgpt7** [comment]
Hey @kiudee Here's another repository's analysis report with some extensive issues detected (bug-risks and performance issues in addition to just style issues): https://deepsource.io/gh/akshgpt7/luigi/issues/?category=recommended

**Comment by akshgpt7** [comment]
@kiudee any help that you need with this?

**Comment by kiudee** [comment]
Sorry @akshgpt7, was very busy these last few weeks. I decided to merge the pull request.
Thank you for the contribution!

**Pull request merged**
